title: CS Notes
description: A collection of notes on computer science topics.
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme

# Define the pages that will appear in the navigation bar
header_pages:
  - index.md
  - computer-architecture.md
  - data-structures.md
  - algorithms.md
  - string-concepts.md
  - complexity-analysis.md
  - glossary.md

# Optional: additional configuration for navigation order